import { NextResponse } from "next/server";
import { db } from "@/lib/firebaseAdmin"; // adjust path to your firebase-admin init

import { toNumber } from "@/lib/helper.js";

// ── POST: Generate / Save monthly payroll ───────────────────────────────────
export async function POST(request) {
  try {
    const body = await request.json();
    console.log("Received payroll data:", body);

    const {
      adminId,
      generatedBy,
      headId,
      schoolId,
      monthKey,      // e.g. "2026_07"
      monthLabel,    // e.g. "July 2026"
      staff,         // array of { id, name, role, salary }
      teachers       // array of { id, name, role, salary }
    } = body;

    // ── Validation ────────────────────────────────────────────────────────
    const errors = [];

    if (!adminId) errors.push("Admin ID is required");
    if (!headId) errors.push("Head ID is required");
    if (!schoolId) errors.push("School ID is required");
    if (!generatedBy) errors.push("Generated By is required");
    if (!monthKey) errors.push("Month key is required");
    if (!monthLabel) errors.push("Month label is required");

    if (!Array.isArray(staff)) errors.push("Staff must be an array");
    if (!Array.isArray(teachers)) errors.push("Teachers must be an array");

    if (errors.length > 0) {
      return NextResponse.json(
        { success: false, message: errors.join(". ") },
        { status: 400 }
      );
    }

    // ── Normalize staff & teachers, validate each entry ─────────────────────
    const normalizedStaff = (staff || []).map((s, idx) => {
      if (!s.name?.trim()) errors.push(`Staff #${idx + 1}: name is required`);
      if (!s.role?.trim()) errors.push(`Staff #${idx + 1}: role is required`);
      return {
        id: s.id || `STAFF_${Date.now()}${idx}`,
        name: s.name?.trim() || "",
        role: s.role?.trim() || "",
        salary: toNumber(s.salary)
      };
    });

    const normalizedTeachers = (teachers || []).map((t, idx) => {
      if (!t.name?.trim()) errors.push(`Teacher #${idx + 1}: name is required`);
      if (!t.role?.trim()) errors.push(`Teacher #${idx + 1}: role is required`);
      return {
        id: t.id || `TEACHER_${Date.now()}${idx}`,
        name: t.name?.trim() || "",
        role: t.role?.trim() || "",
        salary: toNumber(t.salary)
      };
    });

    if (errors.length > 0) {
      return NextResponse.json(
        { success: false, message: errors.join(". ") },
        { status: 400 }
      );
    }

    // ── Auto-calculate totals (server is source of truth) ───────────────────
    const staffCount = normalizedStaff.length;
    const staffTotal = normalizedStaff.reduce((sum, s) => sum + toNumber(s.salary), 0);

    const teacherCount = normalizedTeachers.length;
    const teacherTotal = normalizedTeachers.reduce((sum, t) => sum + toNumber(t.salary), 0);

    const totalExpense = staffTotal + teacherTotal;

    // ── Prevent duplicate payroll for same school + month ───────────────────
    const docId = `${schoolId}_${monthKey}`;
    const payrollRef = db.collection("PayrollReports").doc(docId);
    const existingSnap = await payrollRef.get();

    if (existingSnap.exists) {
      return NextResponse.json(
        {
          success: false,
          message: `Payroll for ${monthLabel} already exists for this school. Use PUT to update it.`
        },
        { status: 409 }
      );
    }

    // ── Build payroll document ───────────────────────────────────────────────
    const payrollDoc = {
      adminId,
      generatedAt: new Date().toISOString(),
      generatedBy,
      headId,
      schoolId,
      monthKey,
      monthLabel,
      staff: normalizedStaff,
      staffCount,
      staffTotal,
      teachers: normalizedTeachers,
      teacherCount,
      teacherTotal,
      totalExpense
    };

    // ── Save to Firestore ────────────────────────────────────────────────────
    await payrollRef.set(payrollDoc);

    return NextResponse.json(
      {
        success: true,
        message: `Payroll for ${monthLabel} generated successfully`,
        payrollId: docId,
        data: payrollDoc
      },
      { status: 201 }
    );
  } catch (error) {
    console.error("Payroll POST error:", error);
    return NextResponse.json(
      { success: false, message: "Failed to save payroll record. Please try again." },
      { status: 500 }
    );
  }
}

// ── PUT: Update an existing payroll (re-generate for same month) ───────────
export async function PUT(request) {
  try {
    const { searchParams } = new URL(request.url);
    const schoolId = searchParams.get("schoolId");
    const monthKey = searchParams.get("monthKey");
    const body = await request.json();

    const { adminId, generatedBy, headId, monthLabel, staff, teachers } = body;

    const errors = [];
    if (!schoolId) errors.push("School ID is required");
    if (!monthKey) errors.push("Month key is required");
    if (!adminId) errors.push("Admin ID is required");
    if (!headId) errors.push("Head ID is required");
    if (!generatedBy) errors.push("Generated By is required");
    if (!monthLabel) errors.push("Month label is required");
    if (!Array.isArray(staff)) errors.push("Staff must be an array");
    if (!Array.isArray(teachers)) errors.push("Teachers must be an array");

    if (errors.length > 0) {
      return NextResponse.json(
        { success: false, message: errors.join(". ") },
        { status: 400 }
      );
    }

    const docId = `${schoolId}_${monthKey}`;
    const payrollRef = db.collection("PayrollReports").doc(docId);
    const existingSnap = await payrollRef.get();

    if (!existingSnap.exists) {
      return NextResponse.json(
        { success: false, message: "Payroll record not found for this school/month" },
        { status: 404 }
      );
    }

    const normalizedStaff = staff.map((s, idx) => ({
      id: s.id || `STAFF_${Date.now()}${idx}`,
      name: s.name?.trim() || "",
      role: s.role?.trim() || "",
      salary: toNumber(s.salary)
    }));

    const normalizedTeachers = teachers.map((t, idx) => ({
      id: t.id || `TEACHER_${Date.now()}${idx}`,
      name: t.name?.trim() || "",
      role: t.role?.trim() || "",
      salary: toNumber(t.salary)
    }));

    const staffCount = normalizedStaff.length;
    const staffTotal = normalizedStaff.reduce((sum, s) => sum + toNumber(s.salary), 0);
    const teacherCount = normalizedTeachers.length;
    const teacherTotal = normalizedTeachers.reduce((sum, t) => sum + toNumber(t.salary), 0);
    const totalExpense = staffTotal + teacherTotal;

    const updateData = {
      adminId,
      generatedAt: new Date().toISOString(), // re-generated timestamp
      generatedBy,
      headId,
      monthLabel,
      staff: normalizedStaff,
      staffCount,
      staffTotal,
      teachers: normalizedTeachers,
      teacherCount,
      teacherTotal,
      totalExpense
    };

    await payrollRef.update(updateData);

    const updatedDoc = await payrollRef.get();

    return NextResponse.json({
      success: true,
      message: `Payroll for ${monthLabel} updated successfully`,
      data: { id: updatedDoc.id, ...updatedDoc.data() }
    });
  } catch (error) {
    console.error("Payroll PUT error:", error);
    return NextResponse.json(
      { success: false, message: "Failed to update payroll: " + error.message },
      { status: 500 }
    );
  }
}

// ── GET: Fetch payroll(s) ────────────────────────────────────────────────────
// - schoolId + monthKey → single payroll record
// - schoolId only       → all payrolls for that school
export async function GET(request) {
  try {
    const { searchParams } = new URL(request.url);
    const schoolId = searchParams.get("schoolId");
    const monthKey = searchParams.get("monthKey");

    if (!schoolId) {
      return NextResponse.json(
        { success: false, message: "School ID is required" },
        { status: 400 }
      );
    }

    if (monthKey) {
      // Single month record
      const docId = `${schoolId}_${monthKey}`;
      const docSnap = await db.collection("PayrollReports").doc(docId).get();

      if (!docSnap.exists) {
        return NextResponse.json(
          { success: false, message: "No payroll found for this school/month" },
          { status: 404 }
        );
      }

      return NextResponse.json({
        success: true,
        payroll: { id: docSnap.id, ...docSnap.data() }
      });
    }

    // All payrolls for the school, most recent month first
    const snap = await db
      .collection("PayrollReports")
      .where("schoolId", "==", schoolId)
      .orderBy("monthKey", "desc")
      .get();

    const payrolls = snap.docs.map((d) => ({ id: d.id, ...d.data() }));

    return NextResponse.json({ success: true, payrolls });
  } catch (error) {
    console.error("Payroll GET error:", error);
    return NextResponse.json(
      { success: false, message: "Failed to fetch payroll: " + error.message },
      { status: 500 }
    );
  }
}

// ── DELETE: Remove a payroll record ─────────────────────────────────────────
export async function DELETE(request) {
  try {
    const { searchParams } = new URL(request.url);
    const schoolId = searchParams.get("schoolId");
    const monthKey = searchParams.get("monthKey");

    if (!schoolId || !monthKey) {
      return NextResponse.json(
        { success: false, message: "School ID and Month key are required" },
        { status: 400 }
      );
    }

    const docId = `${schoolId}_${monthKey}`;
    const docRef = db.collection("PayrollReports").doc(docId);
    const docSnap = await docRef.get();

    if (!docSnap.exists) {
      return NextResponse.json(
        { success: false, message: "Payroll record not found" },
        { status: 404 }
      );
    }

    await docRef.delete();

    return NextResponse.json({
      success: true,
      message: "Payroll record deleted successfully"
    });
  } catch (error) {
    console.error("Payroll DELETE error:", error);
    return NextResponse.json(
      { success: false, message: "Failed to delete payroll: " + error.message },
      { status: 500 }
    );
  }
}